# Generated by Django 5.0 on 2024-01-14 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nesModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('f_reg', models.CharField(max_length=255, verbose_name='FECHA DE REGISTRO')),
                ('aspirante', models.CharField(max_length=255, verbose_name='NOMBRE ASPIRANTE')),
                ('categoria', models.CharField(max_length=255, verbose_name='CATEGORIA ASPIRANTE')),
                ('cel1', models.CharField(max_length=255, verbose_name='# CELULAR')),
                ('cel2', models.CharField(max_length=255, verbose_name='# CELULAR2')),
                ('apoyo', models.CharField(max_length=255, verbose_name='APOYO')),
                ('observaciones', models.CharField(max_length=255, verbose_name='OBSERVACIONES')),
                ('zona', models.CharField(max_length=255, verbose_name='ZONA')),
                ('status', models.CharField(max_length=255, verbose_name='STATUS')),
                ('f_exam', models.CharField(max_length=255, verbose_name='FECHA EXAMEN')),
                ('f_env_admi', models.CharField(max_length=255, verbose_name='')),
                ('r_exam', models.CharField(max_length=255, verbose_name='RESULTADO EXAMEN')),
                ('solicitud', models.CharField(max_length=255, verbose_name='SOLICITUD')),
                ('audiencia', models.CharField(max_length=255, verbose_name='AUDIENCIA')),
                ('paq', models.CharField(max_length=255, verbose_name='# DE PAQUETE')),
            ],
        ),
    ]
