# Generated by Django 5.0 on 2024-01-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlnes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nesmodel',
            old_name='audiencia',
            new_name='f_audiencia',
        ),
        migrations.AlterField(
            model_name='nesmodel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='nesmodel',
            table='propuestastbl',
        ),
    ]
