# Generated by Django 5.0 on 2024-01-14 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlnes', '0002_rename_audiencia_nesmodel_f_audiencia_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='nesmodel',
            table=None,
        ),
    ]
