# Generated by Django 5.0 on 2024-01-14 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlnes', '0003_alter_nesmodel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='nesmodel',
            table='propuestastbl',
        ),
    ]
